M48
; DRILL file {KiCad 8.0.1} date 2024-04-12T11:27:57-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-12T11:27:57-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X136.032Y-115.685
X136.032Y-120.535
T2
X139.062Y-115.385
X139.062Y-120.835
M30
